package np.edu.nast.payroll.Payroll.service.impl;

import np.edu.nast.payroll.Payroll.entity.DeductionHead;
import np.edu.nast.payroll.Payroll.repository.DeductionHeadRepository;
import np.edu.nast.payroll.Payroll.service.DeductionHeadService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class DeductionHeadServiceImpl implements DeductionHeadService {

    @Autowired
    private DeductionHeadRepository repository;

    @Override
    public DeductionHead saveDeductionHead(DeductionHead head) {
        return repository.save(head); // ID auto-generated by DB
    }

    @Override
    public List<DeductionHead> getAllDeductionHeads() {
        return repository.findAll();
    }

    @Override
    public DeductionHead getDeductionHeadById(Integer id) {
        return repository.findById(id).orElse(null);
    }

    @Override
    public void deleteDeductionHead(Integer id) {
        repository.deleteById(id);
    }
}
